title: "toopazo"
author: "Tomás Opazo"
description: "Mi nombre es Tomás Opazo, chileno, casado y padre de un retoño. 
El 2021 me gradué como PhD en Ing Aeroespacial en PennState (PA, EEUU), 
allí me especialicé en optimización de sistemas dinámicos 
y control de UAV (aviones no tripulados). Actualmente vivo en Santiago y trabajo en 
una empresa de IA para el retail. Mi linea de trabajo es visión computacional y 
reconocimiento de acciones (action recognition). En este blog escribo acerca de cosas 
de mi trabajo y otros temas personales."
permalink: /:title/
lang: "es"
excerpt_separator: "\n\n\n"
date_format: "%d %m, %Y"

# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.html"}
  - {file: "about.md"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:toopazo@proton.me"}
  - {title: Github, icon: github, url: "https://github.com/toopazo"}
  - {title: Subscribe, icon: rss, url: "/feed.xml"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed

exclude:
  - excluded
